spring.application.name=threatguard_demo
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.fhnrrqdptjeotfgahhdt
spring.datasource.password=03gDSpqg1m2l2v1J
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.ssl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dupanisha@gmail.com
spring.mail.password=orit dxit wxiv gkps
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=CHAR
gemini.api.key=AIzaSyASkG_6ziAyDE1VjbPrwVJO2pQksIeFJo8
