spring.application.name=threatguard_demo
spring.datasource.url=jdbc:mysql://localhost:3306/threatguard
spring.datasource.username=root
spring.datasource.password=Upanisha10$
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dupanisha@gmail.com
spring.mail.password=orit dxit wxiv gkps
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=CHAR
gemini.api.key=AIzaSyASkG_6ziAyDE1VjbPrwVJO2pQksIeFJo8
